server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push 

scrape_configs:
  - job_name: fastapi-loguru
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi
          __path__: /var/log/fastapi.log
    pipeline_stages:
      - regex:
          expression: '^\d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2} \| (?P<level>[A-Z]+) \| (?P<message>.*)'
      - labels:
          level:
      - output:
          source: message
