name: CI Build, Test and Push

on:
  push:
    tags:
      - 'model*'  # Executa para qualquer tag que comece com 'model', como model_titanic

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build FastAPI Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-image:${{ github.ref_name }} ./fastapi

      - name: Run tests inside container
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-image:${{ github.ref_name }} bash -c "pytest tests -v"

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-image:${{ github.ref_name }}
